CREATE TABLE CATEGORIAS 
(
  CATEGORIAID NUMBER(*, 0) NOT NULL 
, NOMBRECAT CHAR(50 BYTE) NOT NULL 
, CONSTRAINT PK_CATEGORIAS PRIMARY KEY 
  (
    CATEGORIAID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CATEGORIAS ON CATEGORIAS (CATEGORIAID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE PROVEEDORES 
(
  PROVEEDORID NUMBER(*, 0) NOT NULL 
, NOMBREPROV CHAR(50 BYTE) NOT NULL 
, CONTACTO CHAR(50 BYTE) NOT NULL 
, CELUPROV CHAR(12 BYTE) 
, FIJOPROV CHAR(12 BYTE) 
, CONSTRAINT PK_PROVEEDORES PRIMARY KEY 
  (
    PROVEEDORID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_PROVEEDORES ON PROVEEDORES (PROVEEDORID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE PRODUCTOS 
(
  PRODUCTOID NUMBER(*, 0) NOT NULL 
, PROVEEDORID NUMBER(*, 0) NOT NULL 
, CATEGORIAID NUMBER(*, 0) NOT NULL 
, DESCRIPCION CHAR(50 BYTE) 
, PRECIOUNIT NUMBER NOT NULL 
, EXISTENCIA NUMBER(*, 0) NOT NULL 
, CONSTRAINT PK_PRODUCTOS PRIMARY KEY 
  (
    PRODUCTOID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_PRODUCTOS ON PRODUCTOS (PRODUCTOID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE PRODUCTOS
ADD CONSTRAINT FK_PRODUCTO_CATE_PROD_CATEGORI FOREIGN KEY
(
  CATEGORIAID 
)
REFERENCES CATEGORIAS
(
  CATEGORIAID 
)
ENABLE;

ALTER TABLE PRODUCTOS
ADD CONSTRAINT FK_PRODUCTO_PROV_PROD_PROVEEDO FOREIGN KEY
(
  PROVEEDORID 
)
REFERENCES PROVEEDORES
(
  PROVEEDORID 
)
ENABLE;
