DECLARE

    --EXTRACT
    CURSOR C_CATEGORIAS IS 
        SELECT * 
        FROM C##_PEDIDOS.CATEGORIAS 
        WHERE NOT EXISTS(

            SELECT 1 
            FROM C##_MIG_PEDIDOS.CATEGORIAS 
            WHERE C##_PEDIDOS.CATEGORIAS.CATEGORIAID = C##_MIG_PEDIDOS.CATEGORIAS.CATEGORIAID

        );
    
    REGISTRO_CATEGORIA C_CATEGORIAS%ROWTYPE; --ROWTYPE: TIPO DE DATO QUE SE ASIGNA A UNA VARIABLE, CUYA ESTRUCTURA ES LA MISMA QUE LA DE UNA FILA DE UNA TABLA O CURSOR 

    CURSOR C_PROVEEDORES IS
        SELECT * 
        FROM C##_PEDIDOS.PROVEEDORES;

    TYPE REGISTRO_PROVEEDORES IS RECORD (

        COD_PROVEEDOR PROVEEDORES.PROVEEDORID%TYPE,
        NOMBRE_PROVEEDOR PROVEEDORES.NOMBREPROV%TYPE,
        CONTACTO_PROVEEDOR PROVEEDORES.CONTACTO%TYPE,
        CELULAR_PROVEEDOR PROVEEDORES.CELUPROV%TYPE,
        TEL_FIJO PROVEEDORES.FIJOPROV%TYPE

    );

    FILA_PROVEEDOR REGISTRO_PROVEEDORES;

    CURSOR C_PRODUCTOS IS
        SELECT * 
        FROM C##_PEDIDOS.PRODUCTOS;

    DATOS_PRODUCTOS C_PRODUCTOS%ROWTYPE;

BEGIN

    OPEN C_CATEGORIAS;

        LOOP
            FETCH C_CATEGORIAS
            INTO REGISTRO_CATEGORIA; 

            EXIT WHEN C_CATEGORIAS%NOTFOUND;

            --LOAD
            INSERT INTO CATEGORIAS VALUES (

                REGISTRO_CATEGORIA.CATEGORIAID,
                REGISTRO_CATEGORIA.NOMBRECAT

            );
            COMMIT;

            DBMS_OUTPUT.PUT_LINE('REGISTRO DE CATEGORIA INSERTADO');

        END LOOP;

    CLOSE C_CATEGORIAS;

    OPEN C_PROVEEDORES;

        FETCH C_PROVEEDORES
        INTO FILA_PROVEEDOR;

        WHILE (C_PROVEEDORES%FOUND) LOOP

            INSERT INTO PROVEEDORES VALUES (

                FILA_PROVEEDOR.COD_PROVEEDOR,
                FILA_PROVEEDOR.NOMBRE_PROVEEDOR,
                FILA_PROVEEDOR.CONTACTO_PROVEEDOR,
                FILA_PROVEEDOR.CELULAR_PROVEEDOR,
                FILA_PROVEEDOR.TEL_FIJO

            );
            COMMIT;

            DBMS_OUTPUT.PUT_LINE('REGISTRO DE PROVEEDOR INSERTADO');

            FETCH C_PROVEEDORES
            INTO FILA_PROVEEDOR;

        END LOOP;

    CLOSE C_PROVEEDORES;

    OPEN C_PRODUCTOS;

        LOOP

            FETCH C_PRODUCTOS
            INTO DATOS_PRODUCTOS;

            EXIT WHEN C_PRODUCTOS%NOTFOUND;

            INSERT INTO PRODUCTOS VALUES (

                DATOS_PRODUCTOS.PRODUCTOID, 
                DATOS_PRODUCTOS.PROVEEDORID, 
                DATOS_PRODUCTOS.CATEGORIAID, 
                DATOS_PRODUCTOS.DESCRIPCION, 
                DATOS_PRODUCTOS.PRECIOUNIT, 
                DATOS_PRODUCTOS.EXISTENCIA

            );
            COMMIT;

            DBMS_OUTPUT.PUT_LINE('REGISTRO DE PRODUCTOS INSERTADO');

        END LOOP;


    CLOSE C_PRODUCTOS;

    EXCEPTION

        WHEN OTHERS THEN

            IF (SQLCODE=-1) THEN
            
                DBMS_OUTPUT.PUT_LINE('OCURRIO UN ERROR');
                DBMS_OUTPUT.PUT_LINE(SQLCODE);
                DBMS_OUTPUT.PUT_LINE(SQLERRM);

            END IF;

        /*WHEN DUP_VAL_ON_INDEX THEN
            DBMS_OUTPUT.PUT_LINE('CODIGO DUPLICADO');
            DBMS_OUTPUT.PUT_LINE(SQLCODE);
            DBMS_OUTPUT.PUT_LINE(SQLERRM);*/

END;

DECLARE

    --NECESITAMOS EL RECORD PARA UTILIZAR EL CURSOR IMPLICITO
    TYPE FILA IS RECORD (

        COD_PROV PROVEEDORES.PROVEEDORID%TYPE,
        NOMBRE_PROV PROVEEDORES.NOMBREPROV%TYPE,
        CONTACTO_PROV PROVEEDORES.CONTACTO%TYPE,
        CELULAR_PROV PROVEEDORES.CELUPROV%TYPE,
        TEL_FIJO PROVEEDORES.FIJOPROV%TYPE

    );

    TYPE TABLA_PROVEEDORES IS TABLE OF FILA;

    DATOS_PROVEEDORES TABLA_PROVEEDORES;

BEGIN

    SELECT *
    BULK COLLECT INTO DATOS_PROVEEDORES
    FROM PROVEEDORES;

    FOR NUMFILA IN  1..SQL%ROWCOUNT LOOP

        DBMS_OUTPUT.PUT_LINE('CODIGO DE PROVEEDOR: ' || DATOS_PROVEEDORES(NUMFILA).COD_PROV);
        DBMS_OUTPUT.PUT_LINE('NOMBRE DE PROVEEDOR: ' || DATOS_PROVEEDORES(NUMFILA).NOMBRE_PROV);
        DBMS_OUTPUT.PUT_LINE('CONTACTO DE PROVEEDOR: ' || DATOS_PROVEEDORES(NUMFILA).CONTACTO_PROV);
        DBMS_OUTPUT.PUT_LINE('CELULAR DE PROVEEDOR: ' || DATOS_PROVEEDORES(NUMFILA).CELULAR_PROV);
        DBMS_OUTPUT.PUT_LINE('TELEFONO FIJO DE PROVEEDOR: ' || DATOS_PROVEEDORES(NUMFILA).TEL_FIJO);
        DBMS_OUTPUT.PUT_LINE(CHR(13));

    END LOOP;

END;

SET SERVEROUTPUT ON;

DECLARE

    --NECESITAMOS EL RECORD PARA UTILIZAR EL CURSOR IMPLICITO
    TYPE FILA IS RECORD (

        COD_PROV PROVEEDORES.PROVEEDORID%TYPE,
        NOMBRE_PROV PROVEEDORES.NOMBREPROV%TYPE,
        CONTACTO_PROV PROVEEDORES.CONTACTO%TYPE,
        CELULAR_PROV PROVEEDORES.CELUPROV%TYPE,
        TEL_FIJO PROVEEDORES.FIJOPROV%TYPE

    );

    TYPE TABLA_PROVEEDORES IS TABLE OF PROVEEDORES%ROWTYPE;

    DATOS_PROVEEDORES TABLA_PROVEEDORES;

BEGIN

    SELECT *
    BULK COLLECT INTO DATOS_PROVEEDORES
    FROM PROVEEDORES;

    FOR NUMFILA IN  1..SQL%ROWCOUNT LOOP

        DBMS_OUTPUT.PUT_LINE('CODIGO DE PROVEEDOR: ' || DATOS_PROVEEDORES(NUMFILA).PROVEEDORID);
        DBMS_OUTPUT.PUT_LINE('NOMBRE DE PROVEEDOR: ' || DATOS_PROVEEDORES(NUMFILA).NOMBREPROV);
        DBMS_OUTPUT.PUT_LINE('CONTACTO DE PROVEEDOR: ' || DATOS_PROVEEDORES(NUMFILA).CONTACTO);
        DBMS_OUTPUT.PUT_LINE('CELULAR DE PROVEEDOR: ' || DATOS_PROVEEDORES(NUMFILA).CELUPROV);
        DBMS_OUTPUT.PUT_LINE('TELEFONO FIJO DE PROVEEDOR: ' || DATOS_PROVEEDORES(NUMFILA).FIJOPROV);
        DBMS_OUTPUT.PUT_LINE(CHR(13));

    END LOOP;

END;

SELECT TO_CHAR(SYSDATE, 'MM-DD-YYYY') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'FMMONTH/DD/YYYY') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'DAY/MM/YYYY') FROM DUAL;



DECLARE

    CURSOR C_PRODUCTOS IS
        SELECT * 
        FROM C##_PEDIDOS.PRODUCTOS;

    DATOS_PRODUCTOS C_PRODUCTOS%ROWTYPE;

BEGIN

    OPEN C_PRODUCTOS;

            LOOP

                FETCH C_PRODUCTOS
                INTO DATOS_PRODUCTOS;

                EXIT WHEN C_PRODUCTOS%NOTFOUND;

                INSERT INTO PRODUCTOS VALUES (

                    DATOS_PRODUCTOS.PRODUCTOID, 
                    DATOS_PRODUCTOS.PROVEEDORID, 
                    DATOS_PRODUCTOS.CATEGORIAID, 
                    DATOS_PRODUCTOS.DESCRIPCION, 
                    DATOS_PRODUCTOS.PRECIOUNIT, 
                    DATOS_PRODUCTOS.EXISTENCIA

                );
                COMMIT;

                DBMS_OUTPUT.PUT_LINE('REGISTRO DE PRODUCTOS INSERTADO');

            END LOOP;


        CLOSE C_PRODUCTOS;

        EXCEPTION

            WHEN OTHERS THEN

                IF (SQLCODE=-1) THEN
                
                    DBMS_OUTPUT.PUT_LINE('OCURRIO UN ERROR');
                    DBMS_OUTPUT.PUT_LINE(SQLCODE);
                    DBMS_OUTPUT.PUT_LINE(SQLERRM);

                END IF;

            /*WHEN DUP_VAL_ON_INDEX THEN
                DBMS_OUTPUT.PUT_LINE('CODIGO DUPLICADO');
                DBMS_OUTPUT.PUT_LINE(SQLCODE);
                DBMS_OUTPUT.PUT_LINE(SQLERRM);*/

END;