REVOKE CREATE SESSION, CREATE ANY TABLE, ALTER ANY TABLE, DROP ANY TABLE, ALTER ANY TABLE, CREATE ANY SEQUENCE, DROP ANY SEQUENCE,
CREATE ANY TRIGGER, DROP ANY TRIGGER, ALTER ANY TRIGGER 
FROM C##_PEDIDOS; --CON REVOKE SOLO SE PUEDE QUITAR LOS PERMISOS QUE EL USUARIO SI TIENE

GRANT CREATE ANY TABLE, ALTER ANY TABLE TO C##_PEDIDOS;

--LOS ROLES SON CONTENEDORES EN DONDE TODOS LOS USUARIOS DENTRO DE EL CONTENEDOR UTILIZAN LOS MISMOS PERMISOS

CREATE ROLE C##_PROGRAMADOR_JUNIOR;

GRANT CREATE SESSION, CREATE ANY TABLE, ALTER ANY TABLE, DROP ANY TABLE, CREATE ANY SEQUENCE, DROP ANY SEQUENCE,
CREATE ANY TRIGGER, DROP ANY TRIGGER, ALTER ANY TRIGGER TO C##_PROGRAMADOR_JUNIOR;

GRANT C##_PROGRAMADOR_JUNIOR TO C##_PEDIDOS;

--LOS BLOQUES ANONIMOS NO TIENEN NOMBRE, POR LO TANTO NO PERMANECE ALMACENADO EN LA BASE DE DATOS O GESTOR
--UN SUBPROGRAMA SI TIENE NOMBRE, SE GUARDA EN EL GESTOR Y, POR TANTO, SE PUEDE UTILIZAR EN CUALQUIER MOMENTO 

--ESTRUCTURA BASE DE UN BLOQUE ANONIMO

DECLARE --ESPACIO PARA DECLARAR VARIABLES
    NOMBRE_PROV VARCHAR2(50 CHAR); --CON LOS TIPOS DE DATOS CHAR, LA FUNCION TRIM NO LIMPIA LOS ESPACIOS EN BLANCOS YA QUE LOS CONSIDERA COMO DATOS FIJOS, CONTRARIO A VARCHAR2
    CELULAR VARCHAR2(12 CHAR);
    TEL_FIJO VARCHAR2 (12 CHAR);
    CONTACTO VARCHAR2(50 CHAR);
BEGIN
    SELECT TRIM(NOMBREPROV), TRIM(CONTACTO), TRIM(CELUPROV), TRIM(FIJOPROV) --SELECT INTO SIRVE PARA OBTENER UN SOLO REGISTRO, POR TANTO, HAY QUE ASEGURARNOS DE QUE LA CONSULTA NO RETORNE VARIOS REGISTROS
    INTO NOMBRE_PROV, CONTACTO, CELULAR, TEL_FIJO --EL ORDEN DE LAS VARIABLES DEBE DE COINCIDIR
    FROM PROVEEDORES WHERE PROVEEDORID = 40;
    
    DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL PROVEEDOR ES: ' || NOMBRE_PROV||'.');
    DBMS_OUTPUT.PUT_LINE('EL CONTACTO DEL PROVEEDOR ES: ' || CONTACTO||'.');
    DBMS_OUTPUT.PUT_LINE('EL NUMERO FIJO DEL PROVEEDOR ES: ' || TEL_FIJO||'.');
    DBMS_OUTPUT.PUT_LINE('EL CELULAR DEL PROVEEDOR ES: ' || CELULAR||'.');
END;

DECLARE
    NOM_EMP VARCHAR2(30 CHAR);
    APELLIDO_EMP VARCHAR2(30 CHAR);
    FECHA_NAC EMPLEADOS.FECHA_NAC%TYPE;
BEGIN 
    SELECT TRIM(NOMBRE), TRIM(APELLIDO), TRIM(FECHA_NAC) 
    INTO NOM_EMP, APELLIDO_EMP, FECHA_NAC 
    FROM EMPLEADOS 
    WHERE EMPLEADOID = 1428;
    
    DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL EMPLEADO ES: ' || NOM_EMP||'.');
    DBMS_OUTPUT.PUT_LINE('EL APELLIDO DEL EMPLEADO ES: ' || APELLIDO_EMP||'.');
    DBMS_OUTPUT.PUT_LINE('LA FECHA DE NACIMIENTO DEL EMPLEADO ES: ' || FECHA_NAC||'.');
END;

SET SERVEROUTPUT ON; --SIRVE PARA HABILITAR LA SALIDA DE DATOS

--CURSOR: Objeto que obtendra los registros de una consulta, se puede entender como una matriz con n filas y m columnas

--FETCH: Funcion que nos mueve a la siguiente fila (si es que la hay)

DECLARE 
    CURSOR C_DATOS_EMP IS SELECT EMP.EMPLEADOID, EMP.NOMBRE, EMP.APELLIDO, EMP.FECHA_NAC, EMP.REPORTA_A, EMP.EXTENSION, JEFE.NOMBRE, JEFE.APELLIDO 
    FROM EMPLEADOS EMP 
    LEFT JOIN EMPLEADOS JEFE
    ON EMP.REPORTA_A = JEFE.EMPLEADOID; --LOS DATOS QUE EL CURSOR ALMACENARÁ
    --ESTO ES UN CURSOR EXPLICITO: AQUEL QUE EL PROGRAMADOR CREA Y ASIGNA UN NONBRE, EL IMPLICITO ES CREADO POR EL COMPILADOR DE PL/SQL
    
    COD_EMP EMPLEADOS.EMPLEADOID%TYPE;
    NOMBRE EMPLEADOS.NOMBRE%TYPE;
    APELLIDO EMPLEADOS.APELLIDO%TYPE;
    FECHA EMPLEADOS.FECHA_NAC%TYPE;
    EXTENSION EMPLEADOS.EXTENSION%TYPE;
    JEFE EMPLEADOS.REPORTA_A%TYPE;
    NOMBRE_JEFE EMPLEADOS.NOMBRE%TYPE;
    APELLIDO_JEFE EMPLEADOS.APELLIDO%TYPE;
BEGIN
    OPEN C_DATOS_EMP;
    
    LOOP
        FETCH C_DATOS_EMP INTO COD_EMP, NOMBRE, APELLIDO, FECHA, JEFE, EXTENSION, NOMBRE_JEFE, APELLIDO_JEFE; --EL ORDEN DE LA TABLA DEBE DE COINCIDIR
        EXIT WHEN C_DATOS_EMP%NOTFOUND; --SE COLOCA LA CONDICIÓN ANTES DEL FETCH PARA ASEGURARNOS DE QUE EL ULTIMO REGISTRO NO SE REPITA
        DBMS_OUTPUT.PUT_LINE('EL CODIGO DEL EMPLEADO ES: ' || COD_EMP);
        DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL EMPLEADO ES: ' || TRIM(NOMBRE) || ' ' || TRIM(APELLIDO));
        DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL JEFE ES: ' || TRIM(NOMBRE_JEFE)|| ' ' || TRIM(APELLIDO_JEFE));
        DBMS_OUTPUT.PUT_LINE(CHR(13));
    END LOOP;
    
    CLOSE C_DATOS_EMP;

END;








