DECLARE 
    CURSOR C_DATOS_EMP IS 
    SELECT EMP.EMPLEADOID, EMP.NOMBRE, EMP.APELLIDO, EMP.FECHA_NAC, EMP.REPORTA_A, EMP.EXTENSION, EMP.SALARIO, JEFE.NOMBRE NOMBRE_JEFE, JEFE.APELLIDO APELLIDO_JEFE
    FROM EMPLEADOS EMP 
    INNER JOIN EMPLEADOS JEFE
    ON EMP.REPORTA_A = JEFE.EMPLEADOID; --LOS DATOS QUE EL CURSOR ALMACENARÁ
    --ESTO ES UN CURSOR EXPLICITO: AQUEL QUE EL PROGRAMADOR CREA Y ASIGNA UN NOMBRE, EL IMPLICITO ES CREADO POR EL COMPILADOR DE PL/SQL
    
    COD_EMP EMPLEADOS.EMPLEADOID%TYPE;
    NOMBRE EMPLEADOS.NOMBRE%TYPE;
    APELLIDO EMPLEADOS.APELLIDO%TYPE;
    FECHA EMPLEADOS.FECHA_NAC%TYPE;
    EXTENSION EMPLEADOS.EXTENSION%TYPE;
    JEFE EMPLEADOS.REPORTA_A%TYPE;
    NOMBRE_JEFE EMPLEADOS.NOMBRE%TYPE;
    APELLIDO_JEFE EMPLEADOS.APELLIDO%TYPE;
    SALARIO EMPLEADOS.SALARIO%TYPE;
BEGIN
    OPEN C_DATOS_EMP;

    FETCH C_DATOS_EMP INTO COD_EMP, NOMBRE, APELLIDO, FECHA, JEFE, EXTENSION, SALARIO, NOMBRE_JEFE, APELLIDO_JEFE;
    
    WHILE (C_DATOS_EMP%FOUND) LOOP 
        DBMS_OUTPUT.PUT_LINE('EL CODIGO DEL EMPLEADO ES: ' || COD_EMP);
        DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL EMPLEADO ES: ' || TRIM(NOMBRE) || ' ' || TRIM(APELLIDO));

        IF ((NOMBRE_JEFE IS NOT NULL) AND (APELLIDO_JEFE IS NOT NULL)) THEN 
            DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL JEFE ES: ' || TRIM(NOMBRE_JEFE)|| ' ' || TRIM(APELLIDO_JEFE));
        ELSE
            DBMS_OUTPUT.PUT_LINE('EL EMPLEADO NO TIENE JEFE ASIGNADO');
        END IF;

        CASE 
            WHEN ((SALARIO >= 15000) AND (SALARIO <= 20000)) THEN
                DBMS_OUTPUT.PUT_LINE('EL EMPLEADO TIENE UN SALARIO BAJO');
            WHEN ((SALARIO >= 20000) AND (SALARIO <= 25000)) THEN
                DBMS_OUTPUT.PUT_LINE('EL EMPLEADO TIENE UN SALARIO MEDIO');
            WHEN ((SALARIO >= 25000) AND (SALARIO <= 30000)) THEN
                DBMS_OUTPUT.PUT_LINE('EL EMPLEADO TIENE UN SALARIO ALTO');
        END CASE;

        --ESTE FETCH ERA NECESARIO, YA QUE AL TERMINAR DE EVALUAR EL CASE, NOS PERMITE AVANZAR HACIA EL SIGUIENTE REGISTRO, DE FORMA QUE NUESTRO WHILE NO TENGA UN CICLO INFINITO
        FETCH C_DATOS_EMP INTO COD_EMP, NOMBRE, APELLIDO, FECHA, JEFE, EXTENSION, SALARIO, NOMBRE_JEFE, APELLIDO_JEFE;

        DBMS_OUTPUT.PUT_LINE(CHR(13));
    END LOOP;
    
    CLOSE C_DATOS_EMP;

END;

DECLARE 
    CURSOR C_DATOS_EMP IS 
    SELECT EMP.EMPLEADOID, EMP.NOMBRE, EMP.APELLIDO, EMP.FECHA_NAC, EMP.REPORTA_A, EMP.EXTENSION, JEFE.NOMBRE NOMBRE_JEFE, JEFE.APELLIDO APELLIDO_JEFE, EMP.SALARIO
    FROM EMPLEADOS EMP 
    LEFT JOIN EMPLEADOS JEFE
    ON EMP.REPORTA_A = JEFE.EMPLEADOID; --LOS DATOS QUE EL CURSOR ALMACENARÁ
    --ESTO ES UN CURSOR EXPLICITO: AQUEL QUE EL PROGRAMADOR CREA Y ASIGNA UN NOMBRE, EL IMPLICITO ES CREADO POR EL COMPILADOR DE PL/SQL
    
    COD_EMP EMPLEADOS.EMPLEADOID%TYPE;
    NOMBRE EMPLEADOS.NOMBRE%TYPE;
    APELLIDO EMPLEADOS.APELLIDO%TYPE;
    FECHA EMPLEADOS.FECHA_NAC%TYPE;
    EXTENSION EMPLEADOS.EXTENSION%TYPE;
    JEFE EMPLEADOS.REPORTA_A%TYPE;
    NOMBRE_JEFE EMPLEADOS.NOMBRE%TYPE;
    APELLIDO_JEFE EMPLEADOS.APELLIDO%TYPE;
    SALARIO EMPLEADOS.SALARIO%TYPE;
    CANTIDAD_REGISTROS NUMBER(10);
BEGIN
    OPEN C_DATOS_EMP;

    SELECT COUNT(*) INTO CANTIDAD_REGISTROS FROM EMPLEADOS;

    FETCH C_DATOS_EMP INTO COD_EMP, NOMBRE, APELLIDO, FECHA, JEFE, EXTENSION, NOMBRE_JEFE, APELLIDO_JEFE, SALARIO;
    
    FOR FILA IN 1..CANTIDAD_REGISTROS LOOP 
        FETCH C_DATOS_EMP INTO COD_EMP, NOMBRE, APELLIDO, FECHA, JEFE, EXTENSION, NOMBRE_JEFE, APELLIDO_JEFE, SALARIO;
        DBMS_OUTPUT.PUT_LINE('EL CODIGO DEL EMPLEADO ES: ' || COD_EMP);
        DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL EMPLEADO ES: ' || TRIM(NOMBRE) || ' ' || TRIM(APELLIDO));

        IF ((NOMBRE_JEFE IS NOT NULL) AND (APELLIDO_JEFE IS NOT NULL)) THEN 
            DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL JEFE ES: ' || TRIM(NOMBRE_JEFE)|| ' ' || TRIM(APELLIDO_JEFE));
        ELSE
            DBMS_OUTPUT.PUT_LINE('EL EMPLEADO NO TIENE JEFE ASIGNADO');
        END IF;

        IF ((SALARIO >= 15000) AND (SALARIO <= 20000)) THEN
            DBMS_OUTPUT.PUT_LINE('EL EMPLEADO TIENE SALARIO BAJO');
            DBMS_OUTPUT.PUT_LINE('SU SALARIO ES: ' || SALARIO);
        ELSIF ((SALARIO >= 20000) AND (SALARIO <= 25000)) THEN
            DBMS_OUTPUT.PUT_LINE('EL EMPLEADO TIENE SALARIO MEDIO');
            DBMS_OUTPUT.PUT_LINE('SU SALARIO ES: ' || SALARIO);
            ELSIF ((SALARIO >= 25000) AND (SALARIO <= 30000)) THEN
                DBMS_OUTPUT.PUT_LINE('EL EMPLEADO TIENE SALARIO ALTO');
                DBMS_OUTPUT.PUT_LINE('SU SALARIO ES: ' || SALARIO);
            END IF;

        DBMS_OUTPUT.PUT_LINE(CHR(13));
    END LOOP;
    
    CLOSE C_DATOS_EMP;

END;

SELECT *
FROM EMPLEADOS;

SET SERVEROUTPUT ON;