REVOKE CREATE SESSION, CREATE ANY TABLE, ALTER ANY TABLE, DROP ANY TABLE, ALTER ANY TABLE, CREATE ANY SEQUENCE, DROP ANY SEQUENCE,
CREATE ANY TRIGGER, DROP ANY TRIGGER, ALTER ANY TRIGGER 
FROM C##_PEDIDOS; --CON REVOKE SOLO SE PUEDE QUITAR LOS PERMISOS QUE EL USUARIO SI TIENE

GRANT CREATE ANY TABLE, ALTER ANY TABLE TO C##_PEDIDOS;

--LOS ROLES SON CONTENEDORES EN DONDE TODOS LOS USUARIOS DENTRO DE EL CONTENEDOR UTILIZAN LOS MISMOS PERMISOS

CREATE ROLE C##_PROGRAMADOR_JUNIOR;

GRANT CREATE SESSION, CREATE ANY TABLE, ALTER ANY TABLE, DROP ANY TABLE, CREATE ANY SEQUENCE, DROP ANY SEQUENCE,
CREATE ANY TRIGGER, DROP ANY TRIGGER, ALTER ANY TRIGGER TO C##_PROGRAMADOR_JUNIOR;

GRANT C##_PROGRAMADOR_JUNIOR TO C##_PEDIDOS;

----------------------------------------------------------------
CREATE USER C##_MIG_PEDIDOS IDENTIFIED BY 1234
DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CREATE ANY TABLE, ALTER ANY TABLE, DROP ANY TABLE, CREATE ANY SEQUENCE, DROP ANY SEQUENCE,
CREATE ANY TRIGGER, DROP ANY TRIGGER, ALTER ANY TRIGGER TO C##_MIG_PEDIDOS;  

--NECESITAMOS DARLE PERMISOS AL USUARIO PARA ACCEDER A LOS OBJETOS DE OTROS USUARIOS, DE FORMA QUE PUEDA REALIZAR CONSULTAS SELECT

GRANT SELECT, INSERT ON C##_PEDIDOS.CATEGORIAS TO C##_MIG_PEDIDOS;
GRANT SELECT, INSERT ON C##_PEDIDOS.PROVEEDORES TO C##_MIG_PEDIDOS;
GRANT SELECT, INSERT ON C##_PEDIDOS.PRODUCTOS TO C##_MIG_PEDIDOS;
REVOKE SELECT, INSERT ON C##_PEDIDOS.CATEGORIAS FROM C##_MIG_PEDIDOS;