REVOKE CREATE SESSION, CREATE ANY TABLE, ALTER ANY TABLE, DROP ANY TABLE, ALTER ANY TABLE, CREATE ANY SEQUENCE, DROP ANY SEQUENCE,
CREATE ANY TRIGGER, DROP ANY TRIGGER, ALTER ANY TRIGGER 
FROM C##_PEDIDOS; --CON REVOKE SOLO SE PUEDE QUITAR LOS PERMISOS QUE EL USUARIO SI TIENE

GRANT CREATE ANY TABLE, ALTER ANY TABLE TO C##_PEDIDOS;

--LOS ROLES SON CONTENEDORES EN DONDE TODOS LOS USUARIOS DENTRO DE EL CONTENEDOR UTILIZAN LOS MISMOS PERMISOS

CREATE ROLE C##_PROGRAMADOR_JUNIOR;

GRANT CREATE SESSION, CREATE ANY TABLE, ALTER ANY TABLE, DROP ANY TABLE, CREATE ANY SEQUENCE, DROP ANY SEQUENCE,
CREATE ANY TRIGGER, DROP ANY TRIGGER, ALTER ANY TRIGGER TO C##_PROGRAMADOR_JUNIOR;

GRANT C##_PROGRAMADOR_JUNIOR TO C##_PEDIDOS;