CREATE SEQUENCE SQ_CLIENTES START WITH 11 INCREMENT BY 1 NOCACHE;
SELECT SQ_CLIENTES.CURRVAL FROM DUAL;
DROP SEQUENCE SQ_CLIENTES;

CREATE SEQUENCE SQ_CLIENTES1 START WITH 1 INCREMENT BY -1 NOCACHE MAXVALUE 11;
CREATE SEQUENCE SQ_CLIENTES1 START WITH 11 INCREMENT BY -1 NOCACHE MAXVALUE 11;
DROP SEQUENCE SQ_CLIENTES1;
SELECT SQ_CLIENTES1.NEXTVAL FROM DUAL;


CREATE SEQUENCE SQ_CLIENTES1 START WITH 1 INCREMENT BY 1 NOCACHE; 

INSERT INTO CLIENTES (

    CEDULA_RUC,
    NOMBRECIA,
    NOMBRECONTACTO,
    DIRECCIONCLI,
    FAX,
    EMAIL,
    CELULAR,
    FIJO

) VALUES (
     
    '1234567', 
    'UNAH',
    'EDUARDO PONCE', 
    'BULEVAR SUYAPA', 
    1234567, 
    'EEPONCE@UNAH.HN', 
    '23455',
    '44422'

);

INSERT INTO CLIENTES (

    CLIENTEID,
    CEDULA_RUC,
    NOMBRECIA,
    NOMBRECONTACTO,
    DIRECCIONCLI,
    FAX,
    EMAIL,
    CELULAR,
    FIJO

) VALUES (
     
     75, --EL TRIGGER REEMPLAZA ESTE VALOR ESPECIFICADO YA QUE ANTES DE QUE SE EJECUTE LA INSERCION, SE EJECUTA EL TRIGGER Y COMPLETA LA LLAVE PRIMARIA
    '1234567', 
    'UNAH-VS',
    'CARLOS PEREZ', 
    'BULEVAR SUYAPA', 
    1234567, 
    'CARLOSP@UNAH.HN', 
    '23455',
    '44422'

);


CREATE OR REPLACE TRIGGER TG_PK_CLIENTES BEFORE INSERT ON CLIENTES
FOR EACH ROW
DECLARE



BEGIN
    
    DBMS_OUTPUT.PUT_LINE(:NEW.CLIENTEID);
    :NEW.CLIENTEID := SQ_CLIENTES.NEXTVAL;
    
END;

SELECT *
FROM CLIENTES
WHERE CEDULA_RUC = '1234567';

CREATE OR REPLACE TRIGGER TG_INGRESA_PRODUCTO BEFORE INSERT ON PRODUCTOS
FOR EACH ROW

DECLARE 

    PRODUCTOID PRODUCTOS.PRODUCTOID%TYPE;
    EXISTE_CODIGO NUMBER(1);

BEGIN

    SELECT NVL(MAX(PRODUCTOID)+1, 1) 
    INTO PRODUCTOID
    FROM PRODUCTOS;

    SELECT COUNT(*) 
    INTO EXISTE_CODIGO
    FROM CATEGORIAS
    WHERE CATEGORIAID = :NEW.CATEGORIAID;

    IF (EXISTE_CODIGO = 1) THEN

        

    ELSE 

        :NEW.CATEGORIAID := 100;

    END IF;

END;