CREATE SEQUENCE SQ_CLIENTES START WITH 11 INCREMENT BY 1 NOCACHE;
SELECT SQ_CLIENTES.CURRVAL FROM DUAL;
DROP SEQUENCE SQ_CLIENTES;

CREATE SEQUENCE SQ_CLIENTES1 START WITH 1 INCREMENT BY -1 NOCACHE MAXVALUE 11;
CREATE SEQUENCE SQ_CLIENTES1 START WITH 11 INCREMENT BY -1 NOCACHE MAXVALUE 11;
DROP SEQUENCE SQ_CLIENTES1;
SELECT SQ_CLIENTES1.NEXTVAL FROM DUAL;


CREATE SEQUENCE SQ_CLIENTES1 START WITH 1 INCREMENT BY 1 NOCACHE; 

INSERT INTO CLIENTES (

    CEDULA_RUC,
    NOMBRECIA,
    NOMBRECONTACTO,
    DIRECCIONCLI,
    FAX,
    EMAIL,
    CELULAR,
    FIJO

) VALUES (
     
    '1234567', 
    'UNAH',
    'EDUARDO PONCE', 
    'BULEVAR SUYAPA', 
    1234567, 
    'EEPONCE@UNAH.HN', 
    '23455',
    '44422'

);

INSERT INTO CLIENTES (

    CLIENTEID,
    CEDULA_RUC,
    NOMBRECIA,
    NOMBRECONTACTO,
    DIRECCIONCLI,
    FAX,
    EMAIL,
    CELULAR,
    FIJO

) VALUES (
     
     75, --EL TRIGGER REEMPLAZA ESTE VALOR ESPECIFICADO YA QUE ANTES DE QUE SE EJECUTE LA INSERCION, SE EJECUTA EL TRIGGER Y COMPLETA LA LLAVE PRIMARIA
    '1234567', 
    'UNAH-VS',
    'CARLOS PEREZ', 
    'BULEVAR SUYAPA', 
    1234567, 
    'CARLOSP@UNAH.HN', 
    '23455',
    '44422'

);


CREATE OR REPLACE TRIGGER TG_PK_CLIENTES BEFORE INSERT ON CLIENTES
FOR EACH ROW
DECLARE



BEGIN
    
    DBMS_OUTPUT.PUT_LINE(:NEW.CLIENTEID);
    :NEW.CLIENTEID := SQ_CLIENTES.NEXTVAL;
    
END;

SELECT *
FROM CLIENTES
WHERE CEDULA_RUC = '1234567';

CREATE OR REPLACE TRIGGER TG_INGRESA_PRODUCTO BEFORE INSERT OR UPDATE ON PRODUCTOS
FOR EACH ROW

DECLARE 

    PRODUCTOID PRODUCTOS.PRODUCTOID%TYPE;
    EXISTE_CODIGO NUMBER(1);

BEGIN

    IF (INSERTING) THEN

        SELECT NVL(MAX(PRODUCTOID)+1, 1) 
        INTO PRODUCTOID
        FROM PRODUCTOS;

        :NEW.PRODUCTOID := PRODUCTOID;
        :NEW.FECHA_INSERCION := SYSTIMESTAMP;

    ELSIF (UPDATING) THEN

        :NEW.FECHA_ACTUALIZACION := SYSTIMESTAMP;

    END IF;

    SELECT COUNT(*) 
    INTO EXISTE_CODIGO
    FROM CATEGORIAS
    WHERE CATEGORIAID = :NEW.CATEGORIAID;

    IF (EXISTE_CODIGO = 0) THEN

        :NEW.CATEGORIAID := 100;

    END IF;

    --VALIDAR EXISTENCIA DE CODIGO DE PROVEEDOR
    SELECT COUNT(*)
    INTO EXISTE_CODIGO
    FROM PROVEEDORES 
    WHERE PROVEEDORID = :NEW.PROVEEDORID;

        IF (EXISTE_CODIGO = 0) THEN

            :NEW.CATEGORIAID := 100;

        END IF;

        IF (EXISTE_CODIGO = 0) THEN

            :NEW.PROVEEDORID := 10;

        END IF;

        IF (:NEW.PRECIOUNIT < 100) THEN

            :NEW.PRECIOUNIT := 200;

        END IF;

        IF (:NEW.EXISTENCIA <= 0) THEN

            :NEW.EXISTENCIA := 5;

        END IF;

    :NEW.FECHA_INSERCION := SYSTIMESTAMP;
    :NEW.FECHA_ACTUALIZACION := SYSTIMESTAMP;
    :NEW.USUARIO := USER; --USER OBTIENE EL USUARIO QUE ESTA CONECTADO A LA BASE DE DATOS
        
END;

INSERT INTO PRODUCTOS (

    PROVEEDORID,
    CATEGORIAID,
    DESCRIPCION,
    PRECIOUNIT,
    EXISTENCIA

) VALUES (

    86857,
    300,
    'ACE',
    320,
    100

);

COMMIT;

ALTER TABLE PRODUCTOS ADD FECHA_INSERCION TIMESTAMP;
ALTER TABLE PRODUCTOS ADD FECHA_ACTUALIZACION TIMESTAMP;
ALTER TABLE PRODUCTOS ADD USUARIO VARCHAR2(50);

CREATE OR REPLACE TRIGGER TG_PRODUCTOS_FECHA_ACT BEFORE UPDATE ON PRODUCTOS
FOR EACH ROW

DECLARE

BEGIN

    :NEW.FECHA_ACTUALIZACION := SYSTIMESTAMP;
    :NEW.USUARIO := USER;

END;

COMMIT;

UPDATE PRODUCTOS 
SET DESCRIPCION = 'CLORO EN PRESENTACION DE GALON', EXISTENCIA = -1, PRECIOUNIT = 250
WHERE PRODUCTOID = 17;

CREATE TABLE TBL_LOG_PRODUCTOS (

    PRODUCTOID NUMBER,
    PROVEEDORID NUMBER,
    CATEGORIAID NUMBER,
    DESCRIPCION CHAR(50),
    PRECIOUNIT NUMBER,
    EXISTENCIA NUMBER,
    USUARIO VARCHAR2(50),
    OPERACION VARCHAR2(50),
    PROVEEDORID_NUEVO NUMBER,
    CATEGORIAID_NUEVO NUMBER,
    DESCRIPCION_NUEVO CHAR(50),
    PRECIOUNIT_NUEVO NUMBER,
    EXISTENCIA_NUEVO NUMBER
    
);

CREATE OR REPLACE TRIGGER TG_LOG_PRODUCTOS AFTER INSERT OR UPDATE OR DELETE ON PRODUCTOS
FOR EACH ROW

DECLARE


BEGIN

    IF (INSERTING) THEN

        INSERT INTO TBL_LOG_PRODUCTOS VALUES (

            :NEW.PRODUCTOID,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            USER,
            'INSERT',
            :NEW.PROVEEDORID,
            :NEW.CATEGORIAID,
            :NEW.DESCRIPCION,
            :NEW.PRECIOUNIT,
            :NEW.EXISTENCIA

        );


    ELSIF (UPDATING) THEN
    
        INSERT INTO TBL_LOG_PRODUCTOS VALUES (

            :NEW.PRODUCTOID,
            :OLD.PROVEEDORID,
            :OLD.CATEGORIAID,
            :OLD.DESCRIPCION,
            :OLD.PRECIOUNIT,
            :OLD.EXISTENCIA,
            USER,
            'UPDATE',
            :NEW.PROVEEDORID,
            :NEW.CATEGORIAID,
            :NEW.DESCRIPCION,
            :NEW.PRECIOUNIT,
            :NEW.EXISTENCIA

        );

    ELSIF (DELETING) THEN

        INSERT INTO TBL_LOG_PRODUCTOS VALUES (

            :OLD.PRODUCTOID,
            :OLD.PROVEEDORID,
            :OLD.CATEGORIAID,
            :OLD.DESCRIPCION,
            :OLD.PRECIOUNIT,
            :OLD.EXISTENCIA,
            USER,
            'DELETE',
            NULL,
            NULL,
            NULL,
            NULL,
            NULL

        );

    END IF;

END;

